.TH "ipbench" "1" "18 Feb 2004" "Ian Wienand" "ipbench"
.SH "NAME"
.LP 
ipbench \- Control an ipbench session
.SH "SYNTAX"
.LP 
ipbench [\fB\-\-plugindir\fP=\fIpath\fP]
.br 
\fB\-\-client\fP=\fIclient_hostname\fP... [\fB\-\-client\-port\fP=\fIport\fP]
.br 
\fB\-\-test\fP=\fItestname\fP \fB\-\-test\-target\fP=\fItest_target_hostname\fP
.br 
[\fB\-\-test\-args\fP=\fIargs\fP] [\fB\-\-test\-port\fP=\fIport\fP] 
.br 
[\fB\-\-target\fP=\fItarget_hostname\fP] [\fB\-\-target\-port\fP=\fIport\fP]
.br 
[\fB\-\-target\-args\fP=\fIargs\fP]
.br 
[\fB\-v\fP] [\fB\-V\fP] [\fB\-h\fP|\fB\-\-help\fP]
.SH "DESCRIPTION"
.LP 
Controls a number of remote testing clients to run a specified test and report their results.
.SH "OPTIONS"
.LP 
.TP 
<fb>\-\-plugindir\fR <\fIpath\fP>
Path to the ipbench test plugins
.TP 
\fB\-\-client\fP=\fIhostname\fP...
Specify a remote client to connect to.  Each client must be running an invocation of \fIipbenchd\fP(1).  You may specify multiple clients by passing the \fB\-\-client\fP argument many times.
.TP 
\fB\-\-client\-port\fP=\fIport\fP
Specify a port to connect to remote client.  This will be global, i.e. all clients will be contacted on this port.
.TP 
\fB\-\-test\fP=\fIname\fP
The test to run.  Use \fI\-h\fP to see a list of possible tests.
.TP 
\fB\-\-test\-args\fP=\fIarguments\fP
Arguments for the test.  See test specific documentation for possible arguments; by leaving this argument out you will get the test defaults.
.TP 
\fB\-\-test\-target\fP=\fIhostname\fP
The target machine that the clients should direct their testing towards.
.TP 
\fB\-\-test\-port\fP=\fIport\fP
The port to run the test on.  Each test has an inbuilt port it will use by default.
.TP 
\fB\-\-target\fP=\fItarget_hostname\fP
If the test has companion test that is run on the target machine, this flag will activate it.  The target machine must be running \fIipbenchtd\fP(1).  See the test documentation for more information about the companion target test.
.TP 
\fB\-\-target\-args\fP=\fIargs\fP
Arguments for the companion test on the target.
.TP 
\fB\-v\fP
Be more verbose.
.TP 
\fB\-V\fP
Show version information.
.TP 
\fB\-h\fP | \fB\-\-help\fP
Show help information.
.SH "FILES"
.LP 
(none)
.SH "ENVIRONMENT VARIABLES"
.LP 
(none)
.SH "EXAMPLES"
.LP 
The latency test might be run as:
.LP 
ipbench \-\-client=tinny0 \-\-client=tinny1 \-\-client\-port=6123
.br 
\-\-test\-target=leffe \-\-test=latency \-\-test\-port=5555
.br 
\-\-target=leffe \-\-target\-port=6666
.br 
\-\-test\-args="bps=100000000,size=128,warmup=10,cooldown=10"
.SH "AUTHORS"
.LP 
Ian Wienand <ianw@gelato.unsw.edu.au>
.SH "SEE ALSO"
.LP 
ipbenchd(1) ipbenchtd(1)
