.TH "ipbench" "1" "Dec 2023" "Ian Wienand, Matthew Rossouw" "ipbench"
.SH "NAME"
.LP 
ipbench \- Control an ipbench session
.SH "SYNTAX"
.HP 
ipbench [\fB\-t\fP <\fItest\fP>|\fB\-\-test\fP=<\fItest\fP>]
[\fB\-c\fP <\fIclient\fP>|\fB\-\-client\fP=<\fIclient\fP> ...]
.br
[\fB\-p\fP <\fIport\fP>|\fB\-\-port\fP=<\fIport\fP>]
[\fB\-\-config\fP=<\fIconfig\fP>]
[\fB\-a\fP <\fIargs\fP>|\fB\-\-test\-args\fP=<\fIargs\fP>]
.br
[\fB\-r\fP|\fB\-\-reset\fP]
[\fB\-T\fP <\fIhostname\fP>|\fB\-\-test\-target\fP=<\fIhostname\fP>]
.br
[\fB\-P\fP <\fIport\fP>|\fB\-\-test\-port\fP=<\fIport\fP>]
[\fB\-\-target\-test\fP=<\fItarget-test\fP>]
.br
[\fB\-\-target\-test\-hostname\fP=<\fIhostname\fP>]
[\fB\-\-target\-test\-args\fP=<\fIargs\fP>]
.br
[\fB\-\-target\-test\-port\fP=<\fIport\fP>]
[\fB\-\-target\-controller\-args\fP=<\fIargs\fP>]
.br
[\fB\-\-target\-test\-controller\-args\fP=<\fIargs\fP>]
[\fB\-d\fP|\fB--debug\fP]
.LP
ipbench [\fB\-h\fP|\fB\-\-help\fP]
.LP
ipbench \fB\-\-version\fP
.SH "DESCRIPTION"
.LP 
Controls a number of remote testing clients to run a specified test and report their results.
.SH "OPTIONS"
.LP
.TP
\fB\-p\fP <\fIport\fP>|\fB\-\-port\fP=<\fIport\fP>
Specify a port to connect to remote clients.
.TP
\fB\-\-config\fP=<\fIconfig\fP>
Specify an input config file (XML based, see documentation).
.TP
\fB\-c\fP <\fIclient\fP>|\fB\-\-client\fP=<\fIclient\fP>
Specify a remote client to connect to. Repeat for multiple clients.
.TP
\fB\-t\fP <\fItest\fP>|\fB\-\-test\fP=<\fItest\fP>
The test to run.
.TP 
\fB\-a\fP <\fIargs\fP>|\fB\-\-test\-args\fP=<\fIargs\fP>
Arguments for the test.
.TP
\fB\-r\fP|\fB\-\-reset\fP
Send an ABORT before setup.
.TP 
\fB\-T\fP <\fIhostname\fP>|\fB\-\-test\-target\fP=<\fIhostname\fP>
The target machine that the clients should direct their testing towards.
.TP 
\fB\-P\fP <\fIport\fP>|\fB\-\-test\-port\fP=<\fIport\fP>
The port the target machines should use to run the test on.
.TP
\fB\-\-target\-test\fP=<\fItarget-test\fP>
Companion test to run on the DUT.
.TP 
\fB\-\-target\-test\-hostname\fP=<\fIhostname\fP>
The IP address or hostname to connect to the target test machine.
.TP 
\fB\-\-target\-test\-args\fP=<\fIargs\fP>
Arguments for the companion test to run on the DUT.
.TP 
\fB\-\-target\-test\-port\fP=<\fIport\fP>
Port to talk to the target test daemon.
.TP 
\fB\-\-target\-controller\-args\fP=<\fIargs\fP>
Arguments for the controller for the main test.
.TP 
\fB\-\-target\-test\-controller\-args\fP=<\fIargs\fP>
Arguments for the controller for the target test.
.TP 
\fB\-d\fP|\fB--debug\fP
Enable Debugging; verbose output.
.TP 
\fB\-\-version\fP
Show program's version number and exit.
.TP 
\fB\-h\fP|\fB\-\-help\fP
Show help information.
.SH "FILES"
.LP 
(none)
.SH "ENVIRONMENT VARIABLES"
.LP 
(none)
.SH "EXAMPLES"
.LP 
examples
.SH "AUTHORS"
.LP 
ipbench by Ian Wienand <ianw@gelato.unsw.edu.au>
.br
and Matthew Rossouw <matthew.rossouw@unsw.edu.au>.
.br
Man page by Christopher Irving <c.irving@unsw.edu.au>.
.SH "SEE ALSO"
.LP 
ipbenchd(1) ipbenchtd(1)
